version: "3.7"

services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yape
    networks:
      - net_broker

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - net_broker

  kafka:
    image: confluentinc/cp-enterprise-kafka:5.5.3
    container_name: kafka
    hostname: localhost
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "transaction-created, antifraud-validate, transaction-validate-anti-fraud, transaction-find"
      KAFKA_CONTROLLED_SHUTDOWN_RETRY_BACKOFF_MS: 5000

    ports:
      - 9092:9092
    networks:
      - net_broker
  redis:
        image: redis:3
        restart: always
        container_name: redis
        ports:
        - 6379:6379
        environment:
        - ALLOW_EMPTY_PASSWORD=yes
        volumes: 
        - ./redis:/data
        networks:
        - net_broker

  ms-transaction:
    container_name: ms-transaction
    build:
      context: .
      dockerfile: ms-transaction/Dockerfile
    image: transaction_ms
    restart: always
    depends_on:
      - postgres
      - kafka
    ports:
      - "8000:3000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DATABASE_NAME: yape
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres
      APP_PORT: 3000
      KAFKA_BROKER: kafka:9092
      KAFKA_TRANSACTION_TOPIC: transaction-validate-anti-fraud
      KAFKA_ANTIFRAUD_TOPIC: antifraud-validate
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_TTL: 3600000
    networks:
        - net_broker

  ms-anti-fraud:
      container_name: ms-anti-fraud
      build:
        context: .
        dockerfile: ms-anti-fraud/Dockerfile
      image: antifraud_ms
      restart: always
      depends_on:
        - kafka
      ports:
        - "8081:5000"
      environment:
        APP_PORT: 5000
        KAFKA_BROKER: kafka:9092
        KAFKA_TRANSACTION_VALIDATE_TOPIC: transaction-validate-anti-fraud
        KAFKA_ANTIFRAUD_TOPIC: antifraud-validate
        REJECTED_TRANSACTION_VALUE: 1000
      networks:
          - net_broker

networks:
  net_broker:
    driver: bridge
